---
platform: linux

inputs:
- name: cred-alert
  path: go/src/github.com/pivotal-cf/cred-alert

outputs:
- name: cred-alert-cli-darwin

params:
  GOOS: darwin

run:
  path: go/src/github.com/pivotal-cf/cred-alert/ci/scripts/compile-cli
