---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang

inputs:
- name: cred-alert
  path: go/src/github.com/pivotal-cf/cred-alert

outputs:
- name: release-params

run:
  path: go/src/github.com/pivotal-cf/cred-alert/ci/scripts/create-release
